query Games ($id:ID!){
    player(where: {
        id: $id
    }){
        games {
            id
            players {
                name
            }
            maxPlayers
            questions {
                question
            }
        }
    }
}